# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d02245054b1957eb0efd1e743690614a0cdf9e137db019b35cef2f23e1a3d47c374c4493d9a1f75b7b1cb3bec97142eff6f33165d8268c93ffc1604f3ecede25

test:
  secret_key_base: c8a160c1d7d325326872e6e385cf73cd3cc2457fd20a5dce9921399f7ee98807918cb8bf60dc0fb93714f93370b8b5def288b9655270aed460e5cb3475db986f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
